### ISSUE TITLE
Additional blink attributes - also correct syntax of /Attribute/Blink

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/HED-schema#11]
Add:
/Attribute/Blink/Duration {requireChild}  [Duration of blink, usually the half-height blink duration in seconds taken either from base or zero of EEG signal. For eye-trackers, usually denotes interval when pupil covered by eyelid.]
   (number sing) {takesValue, isNumeric, unitClass=time, default=s}

Fix:
Numerous syntax errors in adding /Attribute/Blink subtree.  Centiseconds is misspelled. Things are in wrong order. [ ] missing around descriptions.  

Also in the units section centiseconds is misspelled.  Also add cs in the units.

**Comment by VisLab** [comment]
The previous comments the number sign on takes value was was misread as markup

/Attribute/BlinkDuration ....
     (number sign) {takesValue, isNumeric, unitClass=time, default=s}

**Comment by bigdelys** [comment]
Fixed, could you please check?

**Comment by VisLab** [comment]
Checked....looks good.  Thanks
