### ISSUE TITLE
Adding additional instructions

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/HED-schema#13]
Add 
Event category/Experimental stimulus/Instruction/Push button
Event category/Experimental stimulus/Instruction/Touch screen
Event category/Experimental stimulus/Instruction/Blink

Also talk about alternative, more orthogonal approaches using /Action with Instruction.

**Comment by bigdelys** [comment]
Made a new major version of HED and moved Event category/Experimental stimulus/Instruction/XXX under to under Action/, grouped with Attribute/Instruction.
