### ISSUE TITLE
provide up-to-date documentation

### ISSUE THREAD

**Issue by robertoostenveld** [BigEEGConsortium/HED-schema#14]
The latest code and documentation that can be downloaded as PDF pertains to HED version 1.31, whereas the wiki mentions version 5.2.3. 

Can the PDF be updated to reflect the latest version?

Can the https://github.com/BigEEGConsortium/HED/blob/master/hed_specification_1.3.xml file be updated to reflect the latest version?

**Comment by VisLab** [comment]
The HED repository under BigEEGConsortium is for HED 1.  The standard is HED 2. The repository for this is HEDTools and is under https://github.com/VisLab/HEDTools/tree/master

We will obviously have to clarify and move.  The currently implementation of the tools will automatically check for an update to the HED hierarchy. We also have a mailing list to be notified of automatic updates to the hierarchy.  Kay Robbins (VisLab)

**Comment by robertoostenveld** [comment]
I recommend to split the HED definition/documentation from the tools. There may be multiple tools (especially if the format gains wider adoption), but there should only be one definition.

**Comment by VisLab** [comment]
This is a good idea.  It will take us a couple of weeks to accomplish this.

**Comment by bigdelys** [comment]
I moved old HED tools to 'old-tools' branch and cleaned up the master branch, pointing from readme.md to  hedtags.org website.
