### ISSUE TITLE
Python HED validation tools?

### ISSUE THREAD

**Issue by sappelhoff** [BigEEGConsortium/HED-schema#27]
In the [paper](https://www.frontiersin.org/articles/10.3389/fninf.2016.00042/full) on HED tags, there is mention of a python validator and the reader is referred to this repository (via the website).

could somebody point me to the python validation tools, please?

**Comment by VisLab** [comment]
https://github.com/VisLab/HEDTools

also there is an online validator at:  http://netdb1.cs.utsa.edu/hed/

**Comment by sappelhoff** [comment]
thanks @VisLab
