### ISSUE TITLE
Need additional paradigm tags.

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/HED-schema#3]
We need to expand the list of paradigm tags in order to start encoding into ESS task tags and HED. We should try to conform to the Cognitive Atlas task list whenever possible. http://www.cognitiveatlas.org/tasks/

For the BCI2000 dataset we need to add in HED
/Paradigm/Eyes open task
/Paradigm/Eyes closed task
/Paradigm/Imagined movement

All from cognitive atlas.  However there is no /Paradigm/Real movement  and perhaps there should also be /Paradigm/Motor imagery task

**Comment by bigdelys** [comment]
What would be the difference between "/Paradigm/Imagined movement" and "/Paradigm/Motor imagery task"?

**Comment by VisLab** [comment]
Because there is a task which is real movement that is a separate dataset.
Example open and close left fist,  open and close right fist.

Here is the description of the task from physionet:

A target appears on either the left or the right side of the screen. The
subject opens and closes the corresponding fist until the target
disappears. Then the subject relaxes.

**Comment by bigdelys** [comment]
Added these paradigms:
* Imagined movement
* Rest
** Rest eyes open
** Rest eyes closed
