### ISSUE TITLE
Need /Attribute/Response time tag

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/HED-schema#4]
Suggest adding
/Attribute/Response time/#       [time between stimulus and finish of the response]
/Attribute/Reaction time/#         [time between stimulus and first response]

**Comment by bigdelys** [comment]
As suggested, I do not think these have enough accuracy in definition to be put in the schema. For example it is not clear what response of reaction these refer to. Also the distinction between them is ambiguous. We can discuss in today's meeting.
