### ISSUE TITLE
Need attribute reorganization and additions for task tags

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/HED-schema#9]
Attribute/Auditory requires a child - suggest removing (also suggest removing require child for visual).  

Suggest adding extension allowed to /Attribute

Suggest adding/reorganizing
/Attribute/Presentation
/Attribute/Presentation/Fraction (require child)
/Attribute/Presentation/Random  (Means that whatever is presented or appears is presented randomly)
/Attribute/Presentation/Cued    (Means that whatever is presented or appears is cued to something else)
/Attribute/Presentation/Background  (Means that whatever is presented is presented in the background such as background music)

**Comment by bigdelys** [comment]
Fixed in HED schema.
